from tkinter import *
from tkinter import messagebox
import subprocess
import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",password="sk270405",database='PyBank')
mycur=mydb.cursor()
from PIL import Image, ImageTk
root=Tk()
def profile1():
    mycur.execute("SELECT * FROM login")
    a = mycur.fetchone()
    account_no = a[0]
    mycur.execute("SELECT * FROM Accounts WHERE account_no=%s", (account_no,))
    data = mycur.fetchone()
    if data is not None:
        # Display the account and balance information
        account.config(text=data[0])  # Assuming the first column is account info
        fname.config(text=data[1])
        birth.config(text=data[2])
        phone.config(text=data[3])
        email.config(text=data[6])
        city.config(text=data[7])
def delete1():
    subprocess.Popen(["Python", "delete.py"])
    root.quit()
def update1():
    subprocess.Popen(["Python", "update.py"])
    root.quit()
def dash():
    subprocess.Popen(["Python","dashboard.py"])
    root.quit()
def profile_view():
    subprocess.Popen(["Python", "view_profile.py"])
    root.quit()
def logout():
    subprocess.Popen(["Python","login.py"])
    root.quit()
root.geometry("1190x550")
frame=Frame(root,width=260,height=650,bg="white")
frame.grid(row=0,column=1)
img = Image.open("card.jpg")
img = img.resize((80, 70), Image.Resampling.LANCZOS)
img = ImageTk.PhotoImage(img)
Label(frame,image=img,bg="white").place(x=10,y=10)
Label(frame,text="PyBank",font=("Calibri",26,'bold'),fg="Orange",bg="white").place(x=110,y=21)
img1 = Image.open("home.jpg")
img1 = img1.resize((30, 30), Image.Resampling.LANCZOS)
img1 = ImageTk.PhotoImage(img1)
Label(frame,image=img1,bg="white",cursor="hand2").place(x=30,y=130)
dashboard=Label(frame,text="Dashboard",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
dashboard.place(x=110,y=131)
dashboard.bind("<Button-1>", lambda e: dash())
##View Profile
img2 = Image.open("viewp.jpg")
img2 = img2.resize((30, 30), Image.Resampling.LANCZOS)
img2 = ImageTk.PhotoImage(img2)
Label(frame,image=img2,bg="white",cursor="hand2").place(x=30,y=180)
profile=Label(frame,text="View Profile",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
profile.place(x=110,y=181)
profile.bind("<Button-1>", lambda e: profile_view())
###Quick transfer
img3 = Image.open("transfer.jpg")
img3 = img3.resize((30, 30), Image.Resampling.LANCZOS)
img3 = ImageTk.PhotoImage(img3)
Label(frame,image=img3,bg="white",cursor="hand2").place(x=30,y=230)
transfer=Label(frame,text="Quick Transfer",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
transfer.place(x=110,y=230)
##DEposit
img4 = Image.open("deposit.jpg")
img4 = img4.resize((25, 25), Image.Resampling.LANCZOS)
img4 = ImageTk.PhotoImage(img4)
Label(frame,image=img4,bg="white",cursor="hand2").place(x=30,y=285)
deposit=Label(frame,text="Deposit",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
deposit.place(x=110,y=285)
##Credit Card
img5 = Image.open("credit.jpg")
img5 = img5.resize((30, 30), Image.Resampling.LANCZOS)
img5 = ImageTk.PhotoImage(img5)
Label(frame,image=img5,bg="white",cursor="hand2").place(x=30,y=330)
credit=Label(frame,text="Credit Card",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
credit.place(x=110,y=330)
##update
img6 = Image.open("update.jpg")
img6 = img6.resize((25, 25), Image.Resampling.LANCZOS)
img6 = ImageTk.PhotoImage(img6)
Label(frame,image=img6,bg="white",cursor="hand2").place(x=30,y=380)
update=Label(frame,text="Update Profile",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
update.place(x=110,y=380)
update.bind("<Button-1>", lambda e: update1())
##loan
# img7 = Image.open("loan.jpg")
# img7 = img7.resize((25, 25), Image.Resampling.LANCZOS)
# img7 = ImageTk.PhotoImage(img7)
# Label(frame,image=img7,bg="white",cursor="hand2").place(x=30,y=430)
# loan=Label(frame,text="Loan",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
# loan.place(x=110,y=430)
##delete
img8 = Image.open("delete.jpg")
img8 = img8.resize((25, 25), Image.Resampling.LANCZOS)
img8 = ImageTk.PhotoImage(img8)
Label(frame,image=img8,bg="white",cursor="hand2").place(x=30,y=430)
delete=Label(frame,text="Delete Account",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
delete.place(x=110,y=430)
delete.bind("<Button-1>", lambda e: delete1())
##logout
img9 = Image.open("logout.jpg")
img9 = img9.resize((22, 22), Image.Resampling.LANCZOS)
img9 = ImageTk.PhotoImage(img9)
Label(frame,image=img9,bg="white",cursor="hand2").place(x=30,y=480)
delete=Label(frame,text="Logout",cursor="hand2",font=("Calibri",14),fg="dark blue",bg="white")
delete.place(x=110,y=480)
delete.bind("<Button-1>", lambda e: logout())


pic = Image.open("viewp1.jpg")
pic = pic.resize((410, 476), Image.Resampling.LANCZOS)
pic = ImageTk.PhotoImage(pic)
Label(root,image=pic,bg="white",cursor="hand2").place(x=730,y=30)
Frame(root,width=460,height=480,bg="white").place(x=320,y=30)
Label(root,text="Account Details",font=("Calibri",22,'bold'),fg="orange",bg="white").place(x=470,y=50)
Label(root,text="Account Holder:",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=150)
account=Label(root,text="Account Holder:",font=("Calibri",14,'bold'),fg="black",bg="white")
account.place(x=560,y=150)
Label(root,text="Father Name:",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=190)
fname=Label(root,text="Father Name:",font=("Calibri",14,'bold'),fg="black",bg="white")
fname.place(x=550,y=190)
Label(root,text="D.O.B(YYYY/MM/DD):",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=230)
birth=Label(root,text="D.O.B(YYYY/MM/DD):",font=("Calibri",14,'bold'),fg="black",bg="white")
birth.place(x=590,y=230)
Label(root,text="Phone no:",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=270)
phone=Label(root,text="Phone no:",font=("Calibri",14,'bold'),fg="black",bg="white")
phone.place(x=500,y=270)
Label(root,text="Email-ID:",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=310)
email=Label(root,text="Email-ID:",font=("Calibri",14,'bold'),fg="black",bg="white")
email.place(x=500,y=310)
Label(root,text="City:",font=("Calibri",15,'bold'),fg="dark blue",bg="white").place(x=400,y=350)
city=Label(root,text="City:",font=("Calibri",14,'bold'),fg="black",bg="white")
city.place(x=500,y=350)
profile1()
root.mainloop()